### ISSUE TITLE
Set up the base code for the project Backend

### ISSUE THREAD

**Issue by salim-hertelli** [sbutz/SoftwareEngineering-WS2023-GreenForce#4]
**Description:**

- Set up a working backend and database server running on Google Cloud Platform (GCP) 

**Acceptance Criteria:**

- [x] GCP project with access for every member.
- [x]  Host Website publicly: Github Pages or Firebase Hosting
- [x] Generate API Keys for App
- [x] Dummy Table

**Comment by sbutz** [comment]
I created a Google Firebase projects and invited all of you using your email addresses.

**Comment by sbutz** [comment]
- [ ] Think about Firebase Hosting vs Github Pages
- [ ] Generate API Keys for App
